add header
MirgradR/yea-market-admin pull request #16
Opened 2024-07-12 11:35 UTC by stepanchaban

Добавил Header. 

Есть слайс, который отвечает за auth, но там вообще ни слова про auth почему мы обрабатываем тут ошибки? Нужна помощь по ведению структуры, прям мини мини гайд, как тут работать с роутами.
![image](https://github.com/user-attachments/assets/3af95ce2-d344-41f7-a408-acc91b3570fd)

2024-07-12 20:37 UTC, PerelomaDenis requested changes

2024-07-12 20:37 UTC, PerelomaDenis commented on src/shared/ui/Icon/assets/index.ts
> -import Logout from './Logout.svg'
Не понятно зачем была удалена иконка логаута

2024-07-12 20:37 UTC, PerelomaDenis commented on src/shared/ui/Logout/Logout.tsx
> +import { LogoutProps } from './logout.model'
Также как с другой иконкой, используй компонент Icon

2024-07-12 20:37 UTC, PerelomaDenis commented on src/widgets/header/ui/Header/Header.tsx
> +    <header className={styles.header}>
Стили не соответствуют макету.
1) Иконки надо поменять местами.
2) добавить бордер внизу
3) Установить высоту хедера согласно макету

2024-07-12 20:37 UTC, PerelomaDenis commented on src/widgets/header/ui/Header/Header.tsx
> +              <Logout />
В задаче я добавил описание, что по кнопке логаута, будет вызываться запрос на разлогирование. Соответственно надо добавить

2024-07-12 20:40 UTC, PerelomaDenis commented
> Добавил Header.
> 
> Есть слайс, который отвечает за auth, но там вообще ни слова про auth почему мы обрабатываем тут ошибки? Нужна помощь по ведению структуры, прям мини мини гайд, как тут работать с роутами. ![image](https://private-user-images.githubusercontent.com/54266933/348247645-3af95ce2-d344-41f7-a408-acc91b3570fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTY5NzIsIm5iZiI6MTcyMDgxNjY3MiwicGF0aCI6Ii81NDI2NjkzMy8zNDgyNDc2NDUtM2FmOTVjZTItZDM0NC00MWY3LWE0MDgtYWNjOTFiMzU3MGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIwMzc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNDJlMWYwMWM0MjYzODc1M2M3NDFiNTk5MWU4NDU5ZDYyMWRjMjk5NmQzNDM4ZGI3NDI5OTNlMjUzNzFhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMHM9Vy9EyMAY49nwWBzPVpkbuNqLhvGWuoFPdRGYhg)

То, что тут лежат ошибки это нормально, так как они относятся к запросам регистрации и авторизации. А сами эти запросы нужно бы конечно перенести из baseApi

2024-07-13 10:42 UTC, stepanchaban commented on src/shared/ui/GoToSite/GoToSite.tsx
> +const GoToSite = ({ onClick, ...props }: GoToSiteProps) => {
Очень удобный компонент, теперь использую его в Header

2024-07-13 10:42 UTC, stepanchaban commented on src/shared/ui/Icon/assets/index.ts
> -import Logout from './Logout.svg'
Сомневался, как нужно было правильно делать. Теперь сомнений нет!

2024-07-15 05:29 UTC, MirgradR approved these changes

2024-07-15 06:18 UTC, PerelomaDenis approved these changes

2024-07-15 06:20 UTC, merged